### ISSUE TITLE
Extension is incompatible with JDK21 in native build

### ISSUE THREAD

**Issue by istosSchulz** [quarkiverse/quarkus-morphia#94]
Having generated a blank Quarkus project with quarkus-morphia extension the native build fails on JDK21 with the following error. Having it run with JDK17 makes this error go away. The mentioned method `java.lang.Object.wait0` was introduced with Virtual Threads coming with JDK21. 

Quarkus version: 3.15.1
JDK version: 21.0.4+7-LTS
Base image used to build: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
quarkus-morphia version: 0.5.0

```
#0 71.62 Error: java.util.concurrent.ExecutionException: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
#0 71.62 To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
#0 71.62 com.oracle.graal.pointsto.util.AnalysisError: java.util.concurrent.ExecutionException: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
#0 71.62 To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:169)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:66)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapObjectArray.readElementValue(ImageHeapObjectArray.java:84)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onObjectReachable(ImageHeapScanner.java:464)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.onObjectReachable(SVMImageHeapScanner.java:156)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$markReachable$5(ImageHeapScanner.java:452)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$14(ImageHeapScanner.java:695)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
#0 71.63        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
#0 71.63        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
#0 71.63        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
#0 71.63        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
#0 71.63        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
#0 71.63        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
#0 71.63 Caused by: java.util.concurrent.ExecutionException: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
#0 71.63 To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
#0 71.63        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
#0 71.63        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:64)
#0 71.63        ... 13 more
#0 71.63 Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
#0 71.63 To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
#0 71.63        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.getOrCreateImageHeapConstant(ImageHeapScanner.java:212)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.getOrCreateImageHeapConstant(SVMImageHeapScanner.java:109)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapConstant(ImageHeapScanner.java:186)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onArrayElementReachable(ImageHeapScanner.java:400)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$patchArrayElement$10(ImageHeapScanner.java:593)
#0 71.63        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.HeapSnapshotVerifier$ScanningObserver.forNonNullArrayElement(HeapSnapshotVerifier.java:228)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.scanArrayElement(ObjectScanner.java:232)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.scanArray(ObjectScanner.java:220)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:391)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.lambda$scanConstant$6(ObjectScanner.java:257)
#0 71.63        ... 8 more
#0 71.63 Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
#0 71.63 To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:268)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:140)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:438)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:417)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:78)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:112)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:83)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.createAccessor(ReflectionFeature.java:187)
#0 71.63        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.getOrCreateAccessor(ReflectionFeature.java:141)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.target.ExecutableAccessorComputer.transform(ExecutableAccessorComputer.java:43)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.computeValue(ComputedValueField.java:366)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:336)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readHostedFieldValue(AnalysisConstantReflectionProvider.java:235)
#0 71.63        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.readHostedFieldValue(SVMImageHeapScanner.java:124)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapInstance(ImageHeapScanner.java:287)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObject(ImageHeapScanner.java:254)
#0 71.63        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$getOrCreateImageHeapConstant$2(ImageHeapScanner.java:205)
#0 71.63        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
#0 71.63        ... 21 more
#0 71.63 ------------------------------------------------------------------------------------------------------------------------
#0 71.63                         3.8s (7.1% of total time) in 101 GCs | Peak RSS: 1.64GB | CPU load: 8.41
#0 71.63 ========================================================================================================================
#0 71.63 Finished generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' in 53.2s.
#0 71.77 [INFO] ------------------------------------------------------------------------
#0 71.77 [INFO] BUILD FAILURE
#0 71.77 [INFO] ------------------------------------------------------------------------
#0 71.78 [INFO] Total time:  01:09 min
#0 71.78 [INFO] Finished at: 2024-10-08T10:20:11Z
#0 71.78 [INFO] ------------------------------------------------------------------------
#0 71.79 [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.15.1:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#0 71.79 [ERROR]        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
#0 71.79 [ERROR]        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:489)
#0 71.79 [ERROR]        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)
#0 71.79 [ERROR]        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
#0 71.79 [ERROR]        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
#0 71.79 [ERROR]        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
#0 71.79 [ERROR]        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#0 71.79 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
#0 71.79 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
#0 71.79 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
#0 71.79 [ERROR]        at java.base/java.lang.Thread.run(Thread.java:1583)
#0 71.79 [ERROR]        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
#0 71.79 [ERROR] -> [Help 1]
#0 71.79 [ERROR]
#0 71.79 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 71.79 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 71.79 [ERROR]
#0 71.79 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 71.79 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
------
Dockerfile.native:14
--------------------
  12 |     RUN chmod +x mvnw
  13 |     RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.8.0:go-offline
  14 | >>> RUN ./mvnw package -Dnative -Dquarkus.native.native-image-xmx=5G
  15 |
  16 |     ## Stage 2 : create the docker final image
--------------------
ERROR: failed to solve: process "/bin/sh -c ./mvnw package -Dnative -Dquarkus.native.native-image-xmx=5G" did not complete successfully: exit code: 1
```

**Comment by istosSchulz** [comment]
I'm currently working on upgrading the extension to Morphia 3 (Snapshot) and current Quarkus version coming with version 5+ of MongoDB driver. The latter two are both incompatible with 0.5.0 of the extension. 

The error still exists and my team and I were quite happy if we could use the extension with Java 21. 

@evanchooly any support would be much appreciated. You can find my efforts [in this fork](https://github.com/istosSchulz/quarkus-morphia).

**Comment by evanchooly** [comment]
I love to hear this.  I know i've been neglecting this extension.  Mostly because I've been working on Morphia 3 changes to make this extension "better."  I'd be happy to provide feedback/guidance/whatever.  You can find several of us on [discord](https://discord.gg/saZsJescBa) if you'd care to discuss.
