### ISSUE TITLE
Incompability with Quarkus 3.15.1 on JDK17 in native mode

### ISSUE THREAD

**Issue by istosSchulz** [quarkiverse/quarkus-morphia#96]
Having generated a blank Quarkus project with quarkus-morphia extension and setting it up for Quarkus 3.15.1 the native build fails on JDK17 with the following error.

Quarkus version: 3.15.1
JDK version: 17.0.12+7
GraalVM version: Mandrel-23.0.5.0-Final
Base image used to build: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
quarkus-morphia version: 0.5.0

```
#0 46.44 [2/8] Performing analysis...  []                                                                        (22.1s @ 1.51GB)
#0 46.45    7,074 (77.09%) of  9,176 types reachable
#0 46.46    8,418 (51.58%) of 16,320 fields reachable
#0 46.52   30,031 (45.68%) of 65,743 methods reachable
#0 46.52    2,323 types,   174 fields, and 1,800 methods registered for reflection
#0 46.53
#0 46.53 Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing dev.morphia.DatastoreImpl.<init>(DatastoreImpl.java:105)
#0 46.53 Parsing context:
#0 46.53    at dev.morphia.Morphia.createDatastore(Morphia.java:54)
#0 46.53    at io.quarkiverse.morphia.MorphiaRecorder.lambda$datastoreSupplier$1(MorphiaRecorder.java:20)
#0 46.53    at io.quarkiverse.morphia.MorphiaRecorder$$Lambda$1422/0x00000007c21d46f0.get(Unknown Source)
#0 46.53    at java.util.OptionalInt.orElseThrow(OptionalInt.java:273)
#0 46.53    at root method.(Unknown Source)
#0 46.53
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:178)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:152)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:110)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.lambda$onObservedUpdate$0(DefaultSpecialInvokeTypeFlow.java:63)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.LightImmutableCollection.forEach(LightImmutableCollection.java:90)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:62)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:583)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:474)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
#0 46.53        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
#0 46.53        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
#0 46.53        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
#0 46.53        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
#0 46.53        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
#0 46.53        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
#0 46.53 Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: dev.morphia.mapping.codec.MorphiaMapCodec. This error is reported at image build time because class dev.morphia.mapping.codec.MorphiaTypesCodecProvider is registered for linking at image build time by command line
#0 46.53        at parsing dev.morphia.mapping.codec.MorphiaTypesCodecProvider.<init>(MorphiaTypesCodecProvider.java:32)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2531)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:169)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3409)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.iterateBytecodesForBlock(SharedGraphBuilderPhase.java:712)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3361)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3203)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1134)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.build(SharedGraphBuilderPhase.java:152)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1026)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:114)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:146)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.parseGraph(AnalysisMethod.java:819)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:784)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:767)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysisGraphDecoder.java:120)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1190)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1173)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1028)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:982)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:871)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:186)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:600)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:854)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:77)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:193)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:583)
#0 46.53        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:165)
#0 46.53        ... 15 more
#0 46.53 Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: dev.morphia.mapping.codec.MorphiaMapCodec. This error is reported at image build time because class dev.morphia.mapping.codec.MorphiaTypesCodecProvider is registered for linking at image build time by command line
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:521)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:515)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:407)
#0 46.53        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedNewInstance(SharedGraphBuilderPhase.java:263)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4510)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4503)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5309)
#0 46.53        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3401)
#0 46.53        ... 44 more
#0 46.53 ------------------------------------------------------------------------------------------------------------------------
#0 46.53                         2.5s (8.0% of total time) in 25 GCs | Peak RSS: 2.23GB | CPU load: 9.24
#0 46.54 ------------------------------------------------------------------------------------------------------------------------
#0 46.54 Produced artifacts:
#0 46.54  /code/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/build-artifacts.json (build_info)
#0 46.54  /code/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner-build-output-stats.json (build_info)
#0 46.54 ========================================================================================================================
#0 46.54 Finished generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' in 30.2s.
#0 46.63 [INFO] ------------------------------------------------------------------------
#0 46.63 [INFO] BUILD FAILURE
#0 46.63 [INFO] ------------------------------------------------------------------------
#0 46.63 [INFO] Total time:  45.262 s
#0 46.63 [INFO] Finished at: 2024-10-08T11:22:40Z
#0 46.63 [INFO] ------------------------------------------------------------------------
#0 46.63 [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.15.1:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#0 46.63 [ERROR]        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
#0 46.63 [ERROR]        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:489)
#0 46.63 [ERROR]        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)
#0 46.63 [ERROR]        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
#0 46.63 [ERROR]        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
#0 46.63 [ERROR]        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
#0 46.63 [ERROR]        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#0 46.63 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
#0 46.63 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
#0 46.63 [ERROR]        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
#0 46.63 [ERROR]        at java.base/java.lang.Thread.run(Thread.java:840)
#0 46.63 [ERROR]        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
#0 46.63 [ERROR] -> [Help 1]
#0 46.63 [ERROR]
#0 46.63 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 46.63 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 46.63 [ERROR]
#0 46.63 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 46.63 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
------
Dockerfile.native:14
--------------------
  12 |     RUN chmod +x mvnw
  13 |     RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.8.0:go-offline
  14 | >>> RUN ./mvnw package -Dnative -Dquarkus.native.native-image-xmx=5G
  15 |
  16 |     ## Stage 2 : create the docker final image
--------------------
ERROR: failed to solve: process "/bin/sh -c ./mvnw package -Dnative -Dquarkus.native.native-image-xmx=5G" did not complete successfully: exit code: 1
```

**Comment by evanchooly** [comment]
finally got things upgraded to quarkus 3.30.5
